### PR TITLE
chore(main): release 11.0.0

### LINKED ISSUE #762: Port codebase to TypeScript
Yet another issue for adding TS support to the project.  This time, however, we'll (hopefully) be doing a full port of the codebase to TS so we can use `tsc` to generate the type declaration files.

This will affect the build system, which may (read, "definitely") break backward compatibility.

See PR #763 for specific tasks.

### PR DESCRIPTION
**Pull request by broofa**
:robot: I have created a release *beep* *boop*
---

### ⚠ BREAKING CHANGES

* refactor v1 internal state and options logic ([#780](https://github.com/uuidjs/uuid/issues/780))
* refactor v7 internal state and options logic, fixes #764 ([#779](https://github.com/uuidjs/uuid/issues/779))
* Port to TypeScript, closes  #762 ([#763](https://github.com/uuidjs/uuid/issues/763))
* update node support matrix (only support node 16-20) ([#750](https://github.com/uuidjs/uuid/issues/750))

### Features

* add support for MAX uuid (new in RFC9562) ([#714](https://github.com/uuidjs/uuid/issues/714)) ([0385cd3](https://github.com/uuidjs/uuid/commit/0385cd3f18ae9920678b2849932fa7a9d9aee7d0))
* Port to TypeScript, closes  [#762](https://github.com/uuidjs/uuid/issues/762) ([#763](https://github.com/uuidjs/uuid/issues/763)) ([1e0f987](https://github.com/uuidjs/uuid/commit/1e0f9870db864ca93f7a69db0d468b5e1b7605e7))
* support v6 uuids ([#754](https://github.com/uuidjs/uuid/issues/754)) ([c4ed13e](https://github.com/uuidjs/uuid/commit/c4ed13e7159d87c9e42a349bdd9dc955f1af46b6))
* update node support matrix (only support node 16-20) ([#750](https://github.com/uuidjs/uuid/issues/750)) ([883b163](https://github.com/uuidjs/uuid/commit/883b163b9ab9d6655bfbd8a35e61a3c71674dfe1))
* v8 support ([#759](https://github.com/uuidjs/uuid/issues/759)) ([35a5342](https://github.com/uuidjs/uuid/commit/35a53428202657e402e6b4aa68f56c08194541bf))

### Bug Fixes

* missing v7 expectations in browser spec ([#751](https://github.com/uuidjs/uuid/issues/751)) ([f54a866](https://github.com/uuidjs/uuid/commit/f54a866cedb2b3b96581157c1f4ac935a0b11411))
* refactor v1 internal state and options logic ([#780](https://github.com/uuidjs/uuid/issues/780)) ([031b3d3](https://github.com/uuidjs/uuid/commit/031b3d3d738bc6694501ac0a37152b95ed500989))
* refactor v7 internal state and options logic, fixes [#764](https://github.com/uuidjs/uuid/issues/764) ([#779](https://github.com/uuidjs/uuid/issues/779)) ([9dbd1cd](https://github.com/uuidjs/uuid/commit/9dbd1cd4177c43fcaac961a3b16fb2d044c9940a))
* remove v4 options default assignment preventing native.randomUUID from being used ([#786](https://github.com/uuidjs/uuid/issues/786)) ([afe6232](https://github.com/uuidjs/uuid/commit/afe62323c4408a824755a39d7b971a8ae06f7199))
* revert "perf: remove superfluous call to toLowerCase ([#677](https://github.com/uuidjs/uuid/issues/677))" ([#738](https://github.com/uuidjs/uuid/issues/738)) ([e267b90](https://github.com/uuidjs/uuid/commit/e267b9073df1d0ce119ee53c0487fe76acb2be37))
* seq_hi shift for byte 6 ([#775](https://github.com/uuidjs/uuid/issues/775)) ([1d532ca](https://github.com/uuidjs/uuid/commit/1d532ca374f181932a24a83fa98f71a5bd4f3e96))
* tsconfig module type ([#778](https://github.com/uuidjs/uuid/issues/778)) ([7eff835](https://github.com/uuidjs/uuid/commit/7eff835cba334ad418f57768c00d15b918a9b419))

### Performance Improvements

* remove superfluous call to toLowerCase ([#677](https://github.com/uuidjs/uuid/issues/677)) ([e53793f](https://github.com/uuidjs/uuid/commit/e53793f5be93413cad68b05b3a339ca23e993342))

### Miscellaneous Chores

* release 11.0.0 ([#805](https://github.com/uuidjs/uuid/issues/805)) ([b003cde](https://github.com/uuidjs/uuid/commit/b003cdeda4c6a7ab525f79b9a3d87d1395a1fb4e))

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Comment by broofa** [comment]
@ctavan: Finally pulling the trigger on enabing release-please here. 🎉

Merging this PR should publish `uuid@11.0.0` to NPM, but this'll be the first actual test of that.

'Wish I could say this has gone smoothly, but there's been a couple hiccups:
* RP initially marked this as version `10.0.0`.  Why?  I don't know.  But  I fixed that by manually overriding the version with #805.  (Note: manual-override like that also provides a way of doing prerelease versions, if all else fails.)
* The CHANGELOG updates here include some outdated commits from pre-v11.  Why?  Again, I don't know.  Maybe something to do with [non-linear git commit history](https://github.com/googleapis/release-please?tab=readme-ov-file#linear-git-commit-history-use-squash-merge)?  'Not at all sure that's the issue here, but I saw something similar with `standard-version` when doing the v11-prerelease, so I suspect it's more an issue with the git repo structure and not RP.

The upshot of this is that I'm hopefull these are one-off issues and that things will go more smoothly moving forward.

Regarding the actual release, it's worth noting that there's no actual changes to the built NPM release.  All the recent code churn has just been fixing up the dev and CI toolchains.

Anyhow... let me know if you have any concerns.

**Review by ctavan — APPROVED** [review]
Looks absolutely awesome, thanks for all the hard work on modernizing this module!

**Comment by broofa** [comment]
@ctavan Note: I've created a `uuidbot` account to use for automated task and updated the PAT used by the RP workflow to one generated from that account.  Moving forward, release PRs should show up as coming from uuidbot instead of me.

I'm sending sharing the account info with you via lastpass, so keep an eye out for that email.  Let me know if there's a better way of sharing.  (I use 1password as well, but lastpass is where I keep this sort of thing.)

**Comment by broofa** [comment]
One last note before merging:  PR is blocked because the commits need to be signed... but I don't see an obvious way of fixing that at the moment.  So yet another reason to allow admins to override and merge anyway.

**Pull request merged**
