### PR TITLE
test: install WebdriverIO packages as optional dev dependencies

### PR DESCRIPTION
**Pull request by ctavan**

### CODE REVIEW

**Comment by ctavan** [comment]
@IgorTodorovskiIBM could you check if this branch now lets you run the `cigtm` test on z/OS?

Something like:

```
npx citgm https://github.com/uuidjs/uuid/archive/extract-webdriver-dependencies.tar.gz
```

(or clone the repo & checkout the `extract-webdriver-dependencies` branch).

**Comment by IgorTodorovskiIBM** [comment]
I just tested it on z/OS and your wrapper solution works perfectly.  Thank you so much!

**Comment by ctavan** [comment]
Cool!

@broofa are you fine with this?

**Comment by broofa** [comment]
Hmm... would https://github.com/bcoe/optional-dev-dependency be helpful here?

**Comment by ctavan** [comment]
Oh, that looks promising. For whatever reason me googling for “optional npm dev dependencies” didn’t find it. I will give it a try!

**Comment by ctavan** [comment]
@IgorTodorovskiIBM based on @broofa's feedback I've now chosen a more elegant approach. Would you mind verifying that CITGM still passes on z/OS once again before we merge this?

**Comment by IgorTodorovskiIBM** [comment]
Very cool! CITGM still passes!  Thanks!

**Comment by ctavan** [comment]
Thank you for your help in testing this, @IgorTodorovskiIBM!

**Pull request merged**
