### PR TITLE
docs: add information on usage from React Native

### LINKED ISSUE #375: Version >=7.0.0 is not compatible with React Native / Expo
When I'm upgrading from 3.4.0 to 7.0.0 an error saying it can't require "crypto" pops up in a React Native app. It used to work fine before.

### PR DESCRIPTION
**Pull request by LinusU**
Closes #375

This adds information on how to get the library working on React Native to the readme.

-----

I've verified that this works by:

1. creating a new React Native project (`npx react-native init uuidtest`)
2. added the dependencies (`npm add react-native-get-random-values uuid`)
3. imported the polyfill (`import 'react-native-get-random-values'` in `index.js`)
4. and displayed an UUID in the app (`import * as uuid from 'uuid'` and `{uuid.v4()}` in `App.js`)

### CODE REVIEW

**Comment by LinusU** [comment]
ping @ctavan, this PR is per my comments in #375 ☺️

**Comment by SimenB** [comment]
Does this work in Expo? If not (seems like it's a native lib), a separate section for expo would be ❤️

**Comment by grit96** [comment]
After including that polyfill the errors change to the following on both iOS and Android:

```
'Unhandled promise rejection', { [TypeError: null is not an object (evaluating 'RNGetRandomValues.getRandomBase64')]
```

**Comment by LinusU** [comment]
@SimenB ah right, no it won't. Expo currently doesn't have a sync random api, opening upstream issue now

@grit96 is that on Expo?

**Comment by grit96** [comment]
@LinusU nope, RN 0.59. I just realised that `react-native-get-random-values` probably needs linking because I'm using RN < 0.60.

**Comment by LinusU** [comment]
> probably needs linking because I'm using RN < 0.60

Yeah, that's probably it.

Sorry, I removed the linking step from the readme since I thought that most people would be on >= 0.60 by now ☺️

**Comment by LinusU** [comment]
Issue filed with Expo here: https://github.com/expo/expo/issues/7209

**Pull request merged**
