### PR TITLE
feat: exports regex as 1st class citizen

### PR DESCRIPTION
**Pull request by joaomilho**
This will help the following use case (and others):

```js
import { regex } from 'uuid';

describe('duck', () => {
  it('quacks', () => {
   const duck = createDuck();
    expect(duck).toEqual({
      name: 'daffy',
      sound: 'quack',
      uuid: expect.stringMatching(regex)
    })
  })
})
```

Importing from dist/esm is not ideal, and proper TS support (I think we'll have to change @types/uuid for this) would be great.

### CODE REVIEW

**Comment by broofa** [comment]
See https://github.com/uuidjs/uuid/issues/498#issuecomment-665163121

tl;dr: Allowing users to depend on the regex we use for validate() makes it difficult to modify if/when we need to do so in the future.

Doesn't seem like it's that hard to workaround ...

```javascript
expect({...duck, uuid: uuid.validate(duck.uuid)}).toEqual({
  name: 'daffy',
  sound: 'quack',
  uuid: true
})
```

Or...
```javascript
expect(uuid.validate(duck.uuid)).toBe(true);
expect(duck).toEqual({
   name: 'daffy',
   sound: 'quack',
   uuid: expect.any(String)
});
```

**Comment by broofa** [comment]
Closing due to lack of activity.

**Comment by joaomilho** [comment]
Fair enough. But perhaps a uuid matcher in a diff lib?

```js
describe('duck', () => {
  it('quacks', () => {
   const duck = createDuck();
    expect(duck).toEqual({
      name: 'daffy',
      sound: 'quack',
      uuid: expect.stringMatchingUUIDV4()
    })
  })
})
```

**Comment by piranna** [comment]
> perhaps a uuid matcher in a diff lib?

I like this :-)

**Pull request closed without merging**
