### PR TITLE
fix: small error

### PR DESCRIPTION
**Pull request by 0xflotus**
I only fixed a small typo error

### CODE REVIEW

**Comment by broofa** [comment]
Hey, thanks for the contribution.  [However ...](https://github.com/uuidjs/uuid/blob/main/README.md?plain=1#L1-L3)

**Comment by 0xflotus** [comment]
Ah thanks, I did the fix in the right file.

**Comment by ctavan** [comment]
The generated readme doesn’t match expectations.

Can you ensure there the readme was generated using `npm run docs`?

**Comment by 0xflotus** [comment]
It's easier to open a new PR

**Pull request merged**
