### PR TITLE
Fix problems with jest

### PR DESCRIPTION
**Pull request by alfonsocv12**
Only fix problems with jest

### CODE REVIEW

**Review by walis85300 — APPROVED** [review]

**Review by moisesmorillo — APPROVED** [review]

**Comment by broofa** [comment]
Please elaborate on what problem this is fixing.  Preferably with a minimal, verifiable test case.

**Comment by alfonsocv12** [comment]
I'm using AWS library that depends on this library, my setup is Jest with Typescript, and this lines are giving syntax errors, with that setup specifically.

I know that this works perfectly with vanilla JS, but changing the syntax into this will give support to more use cases.

here is the error message, that I'm getting.

BTW. we fix the issue at our end by ignoring this file

Screenshot 2023-08-20 at 3 39 46 PM

**Comment by ctavan** [comment]
Are you building for Node.js or for the browser?

**Comment by alfonsocv12** [comment]
Node.js

**Comment by ctavan** [comment]
> Node.js

Ok, this looks like some configuration issue in the build chain then: as you can see from the error message, it tries to load the `esm-browser` build of the library, however under Node.js it shouldn’t be loading the browser build.

I would recommend checking the typescript and jest setup for anything related to exports and module handling. You can check other jest related bugs in this repo for inspiration: https://github.com/uuidjs/uuid/issues?q=is%3Aissue+is%3Aclosed+jest

**Comment by ctavan** [comment]
In addition, providing a [minimal
reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) would greatly help us PinPoint and understand the issue.

**Comment by broofa** [comment]
No recipe for reproducing provided.  Closing.

**Pull request closed without merging**
